### testing conv layer

In [1]:
import numpy as np
rng = np.random.default_rng()

In [2]:
from netweaver.layers import LayerConv

Questoin?  
available params (4) - kernel count, kernel size, stride and padding  
1. input image dim = (2, 3, 10, 10) 2 images with 3 channels of size 10 x 10.  
exp 1. kernel count is no of ouput channels for each image. balanced count provides easiness to extract useful patterns.  
exp 2. kernel size is can be odd or even.
exp 3. stride, default is 1. with stride > kernel, skips some pixels. some input and stride mismatches can skips right and bottom values.  
exp 4. padding when with odd kernel, preserves the dim. with even kernel, it reduces by 1.

padding is explicit preserving dimension while stride is to explicitly reduce the dimension.

expectation?
1. exp 1 
    1. input (2, 3, 10/11, 10/11), kernel (4/5, 4/5), stride (equals kernel size)
2. exp 2
3. exp 3
4. exp 4

In [3]:
# exp channels 3, kernel count 3, kernel size 5, padding valid.
images_even_odd = rng.integers(low=-10, high=10, size=(2, 3, 11, 10))
print(images_even_odd.shape)

(2, 3, 11, 10)


In [4]:
con_layer1 = LayerConv(input_channels=3, n_filters=3, filter_size=5, stride=1, padding="valid")
con_layer1.forward(inputs=images_even_odd, training=True)
print(con_layer1.output.shape) # expected = (2, 3, 7, 6)

# with stride 2, reduction of size by 75%
con_layer2 = LayerConv(input_channels=3, n_filters=3, filter_size=5, stride=2, padding="valid")
con_layer2.forward(inputs=images_even_odd, training=True)
print(con_layer2.output.shape) # expected = (2, 3, 4, 3)


(2, 3, 7, 6)
(2, 3, 4, 3)


In [5]:
con_layer1 = LayerConv(input_channels=3, n_filters=3, filter_size=5, stride=1, padding="same")
con_layer1.forward(inputs=images_even_odd, training=True)
print(con_layer1.output.shape)  # expected = (2, 3, 11, 10)

# even filter size
con_layer1 = LayerConv(input_channels=3, n_filters=3, filter_size=4, stride=1, padding="same")
con_layer1.forward(inputs=images_even_odd, training=True)
print(con_layer1.output.shape)  # expected = (2, 3, 10, 9)


(2, 3, 11, 10)
(2, 3, 10, 9)


In [6]:
print(con_layer1.weights.shape)
print(con_layer1)

(3, 3, 4, 4)
Layer_Conv2D(): kernel_count:3 | kernel_channels:3 | kernel_dim:(4,4) | stride:(1,1) | padding:(1,1)


### testing max pooling layer

In [11]:
import numpy as np
rng = np.random.default_rng()

In [12]:
from netweaver.layers import LayerMaxPool2D

In [21]:
#  input with odd height and even width
input_odd_even = rng.integers(low=-10, high=10, size=(2, 3, 11, 10))
print(input_odd_even[:, :, -3:, :])


[[[[  2  -8   0  -9   2   7  -1  -5 -10   7]
   [  0   6  -5  -4  -7  -6   4   4   9  -9]
   [  8   8   6   6   3   5  -1   5   3  -6]]

  [[  5  -4  -5   4 -10  -8  -4   5   7  -7]
   [ -5   8  -7   1  -6  -6 -10   5 -10  -6]
   [ -6   8   5  -1  -5   9  -6  -1 -10   3]]

  [[ -1 -10  -4   8   8 -10  -5   7  -7 -10]
   [  4   4  -4  -5   3  -3   2  -3   2   6]
   [ -2  -1  -6  -6   5   1   9 -10  -4  -5]]]


 [[[  4  -4  -4   3   4  -3   5 -10   3  -1]
   [ -2   1   0   0   3   2  -2  -4   8   3]
   [-10  -8   1  -5 -10 -10   5   5  -5   0]]

  [[ -5   7  -7  -6   1  -4   3 -10   7  -4]
   [  2   9  -2   7   3  -7   8  -9   8  -1]
   [  8  -4  -9   1   8  -1   3  -7  -9  -9]]

  [[ -8  -2  -4  -6   4  -6  -4   9   7   4]
   [  4  -4  -7   1   0   7 -10   8 -10   1]
   [ -9   8   6  -4  -4   2 -10   8  -6 -10]]]]


In [ ]:
# max pooling always applied with stride, make sense. it reduces the dim by extracting important features.
max_layer1 = LayerMaxPool2D(pool_size=(2,2), stride=(2, 2))
max_layer1.forward(input_odd_even, training=True)
print(max_layer1.output.shape) # expected shape (2, 3, 5, 5)
print(max_layer1.output) # expected is last row is skipped due to stride cannot cover.

(2, 3, 5, 5)
[[[[ 9.  8.  8.  9.  6.]
   [ 8.  2.  8. -2.  7.]
   [ 8.  7. -2.  4.  7.]
   [ 7.  9.  9. -3.  8.]
   [ 6.  0.  7.  4.  9.]]

  [[ 7.  5.  4.  7.  7.]
   [ 7.  8.  7.  4.  7.]
   [ 4.  6.  8.  6.  1.]
   [ 8. -2.  8.  9.  9.]
   [ 8.  4. -6.  5.  7.]]

  [[ 3.  7. -2.  6.  8.]
   [ 9.  8.  7.  3.  2.]
   [ 4.  9.  9.  8.  5.]
   [ 8.  8.  8.  6.  9.]
   [ 4.  8.  8.  7.  6.]]]


 [[[ 0.  1.  2.  8.  2.]
   [ 0.  3.  4.  9.  3.]
   [ 4.  8.  2.  9.  1.]
   [ 7.  6.  4.  1.  6.]
   [ 4.  3.  4.  5.  8.]]

  [[ 8.  5.  8.  7.  6.]
   [ 9.  3.  9.  8.  7.]
   [ 1.  1.  9.  3.  7.]
   [ 0.  9.  8.  6.  5.]
   [ 9.  7.  3.  8.  8.]]

  [[ 4.  1.  2.  9.  7.]
   [ 8.  1. -4.  0. -1.]
   [ 8.  9.  8.  7.  7.]
   [-1.  7.  4.  7.  5.]
   [ 4.  1.  7.  9.  7.]]]]


In [24]:
print(max_layer1)

Layer_MaxPool2D(): pool_size: (2,2) | stride: (2,2)


### testing flattening layer

In [1]:
import numpy as np
rng = np.random.default_rng()

In [2]:
inputs = rng.integers(-10, 10, size=(2, 3, 2, 2))
print(inputs.shape)
print(inputs)

(2, 3, 2, 2)
[[[[ 5 -3]
   [-9  7]]

  [[-6  0]
   [-1 -1]]

  [[ 7  3]
   [ 8 -5]]]


 [[[-2 -9]
   [ 9  0]]

  [[ 4 -5]
   [ 3 -4]]

  [[-2 -2]
   [ 7 -5]]]]


In [4]:
from netweaver.layers import LayerFlatten

In [5]:
flat_layer1 = LayerFlatten()
flat_layer1.forward(inputs, training=False)
print(flat_layer1.output.shape) # (2, 12)
print(flat_layer1.output) # notice deserializatoin order

(2, 12)
[[ 5 -3 -9  7 -6  0 -1 -1  7  3  8 -5]
 [-2 -9  9  0  4 -5  3 -4 -2 -2  7 -5]]


In [8]:
flat_layer1.backward(flat_layer1.output)
print(flat_layer1.dinputs.shape) # expected (2, 3, 2, 2)
print(flat_layer1.dinputs) # notice the serialization order


(2, 3, 2, 2)
[[[[ 5 -3]
   [-9  7]]

  [[-6  0]
   [-1 -1]]

  [[ 7  3]
   [ 8 -5]]]


 [[[-2 -9]
   [ 9  0]]

  [[ 4 -5]
   [ 3 -4]]

  [[-2 -2]
   [ 7 -5]]]]


### testing out the whole cnn architecture

In [1]:
from netweaver.model import Model
from netweaver.layers import LayerConv, LayerMaxPool2D, LayerFlatten, LayerDense
from netweaver.activation_layers import ActivationReLU, ActivationSoftmax
from netweaver.lossfunctions import LossCategoricalCrossentropy
from netweaver.optimizers import OptimizerAdam
from netweaver.accuracy import AccuracyCategorical

In [2]:
model = Model()

In [3]:
model.add(LayerConv(input_shape=(1, 28, 28), n_filters=1, filter_size=(3, 3), stride=1, padding="valid"))
model.add(ActivationReLU())
model.add(LayerMaxPool2D(pool_size=(2,2), stride=(2,2)))
model.add(LayerConv(input_shape=(1, 28, 28), n_filters=2, filter_size=(3, 3), stride=1, padding="valid"))
model.add(ActivationReLU())
model.add(LayerMaxPool2D(pool_size=(2, 2), stride=(2, 2)))
model.add(LayerFlatten())

The number of 'n_inputs' for the next dense layer will be 50


In [4]:
model.add(LayerDense(n_inputs=50, n_neurons=16))
model.add(ActivationReLU())
model.add(LayerDense(n_inputs=16, n_neurons=12))
model.add(ActivationReLU())
model.add(LayerDense(n_inputs=12, n_neurons=10))
model.add(ActivationSoftmax())

In [5]:
model.set(loss=LossCategoricalCrossentropy(), optimizer=OptimizerAdam(), accuracy=AccuracyCategorical())

In [6]:
model.finalize()




# Layer_Conv2D(): kernel_count:1 | kernel_channels:1 | kernel_dim:(3,3) | stride:(1,1) | padding:(0,0)| params: 10
------------------------------------------------------------------------------------------------------------------------
# Activation_ReLu()
------------------------------------------------------------------------------------------------------------------------
# Layer_MaxPool2D(): pool_size: (2,2) | stride: (2,2)
------------------------------------------------------------------------------------------------------------------------
# Layer_Conv2D(): kernel_count:2 | kernel_channels:1 | kernel_dim:(3,3) | stride:(1,1) | padding:(0,0)| params: 20
------------------------------------------------------------------------------------------------------------------------
# Activation_ReLu()
------------------------------------------------------------------------------------------------------------------------
# Layer_MaxPool2D(): pool_size: (2,2) | stride: (2,2)
--------------

In [7]:
from netweaver.datasets import load_dataset

In [8]:
data_path = "/home/USER_NETWEAVER/project_netweaver/datasets/fashion_mnist_images"
trian_i, train_g, test_i, test_g = load_dataset(path=data_path)

train set loading:   0%|          | 0/10 [00:00<?, ?labels/s]

test set loading:   0%|          | 0/10 [00:00<?, ?labels/s]

Property                 | instances_train  gtruth_train     instances_test   gtruth_test      
-----------------------------------------------------------------------------------------------
instances count          | 60000            60000            10000            10000            
shape of the set         | (60000, 28, 28)  (60000,)         (10000, 28, 28)  (10000,)         
shape of an instance     | (28, 28)         (1,)             (28, 28)         (1,)             
Data type of unit        | float32          uint8            float32          uint8            
Total memory (gb)        | 0.17524          0.00006          0.02921          0.00001          


train labels count       : 10
train labels values      : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
test labels count        : 10
test labels values       : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
def scale_neg_pos_one(arr, maxvalue):
    max_half = maxvalue / 2
    return (arr - max_half) / max_half


def scale_zero_one(arr, maxvalue):
    return arr / maxvalue

In [14]:
max_value = trian_i.max()
instances_train = scale_zero_one(trian_i, max_value)
instances_test = scale_zero_one(test_i, max_value)

print(instances_train.shape)
print(instances_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [15]:
instances_train = instances_train.reshape(instances_train.shape[0], 1, instances_train.shape[1], instances_train.shape[2])
instances_test = instances_test.reshape(instances_test.shape[0], 1, instances_test.shape[1], instances_test.shape[2])

print(instances_train.shape)
print(instances_test.shape)

(60000, 1, 28, 28)
(10000, 1, 28, 28)


In [16]:
model.train(instances_train, train_g, epochs=10, batch_size=64)

Model Architecture file: /home/USER_NETWEAVER/project_netweaver/rough_room/logs/model_training/model-20250712-000347/model-architecture-20250712-000347.txt
Epoch Log: /home/USER_NETWEAVER/project_netweaver/rough_room/logs/model_training/model-20250712-000347/Log-epoch-20250712-000347.csv
Batch Log: /home/USER_NETWEAVER/project_netweaver/rough_room/logs/model_training/model-20250712-000347/Log-batch-20250712-000347.csv


Training       :   0%|          | 0/10 [00:00<?, ?epoch/s]

Epoch 1       :   0%|          | 0/938 [00:00<?, ?batch/s]

Epoch 2       :   0%|          | 0/938 [00:00<?, ?batch/s]

Epoch 3       :   0%|          | 0/938 [00:00<?, ?batch/s]

Epoch 4       :   0%|          | 0/938 [00:00<?, ?batch/s]

Epoch 5       :   0%|          | 0/938 [00:00<?, ?batch/s]

Epoch 6       :   0%|          | 0/938 [00:00<?, ?batch/s]

Epoch 7       :   0%|          | 0/938 [00:00<?, ?batch/s]

Epoch 8       :   0%|          | 0/938 [00:00<?, ?batch/s]

Epoch 9       :   0%|          | 0/938 [00:00<?, ?batch/s]

Epoch 10      :   0%|          | 0/938 [00:00<?, ?batch/s]